### ISSUE TITLE
Can't handle FontFamily

### ISSUE THREAD

**Issue by jlim521** [cheng-kang/react-native-lahk-marquee-label#3]
I have a custom Font setup and I tried to pass in the font style through `textStyle`. If I do that then no text gets rendered. Is there any workaround that? Thanks!

**Comment by cheng-kang** [comment]
Hi, I just published a new version of this module with this issue fixed. Please use the new version `1.0.4`. 

The problem was when font family is changed to any other than the default font, the `onLayout` event became unable to calculate the correct text size. I added a hidden `Text` component to do the calculation. And now it should work well with custom fonts.

Though I'm still not sure about why this happens because it's fine with another module of mine `[react-native-lahk-marquee-label-vertical](https://github.com/cheng-kang/react-native-lahk-marquee-label-vertical)`. 

It would be great if anyone figures out why and shares it here.

**Comment by jlim521** [comment]
Thanks for updating this! It's accepting custom fonts very well.
One thing that I wish to request is, right now if you change the text, the thing kinda goes all wild. From my understanding, I think you should clear out the x-position when the text props change. I think the texts are going wild because the `Text` length is different. Because right now, the texts are changing while the text is scrolling, and since the text length is different, your `onLayout` logic to calculate the text size is not working as intended. Keep up the good work :)!

**Comment by cheng-kang** [comment]
Just to make it clear, by “right now if you change the text”, do you mean change the text dynamically?

I will take a look at that.

**Comment by jlim521** [comment]
Yes. Thank you!

**Comment by cheng-kang** [comment]
@lykfe Done! The logic is so much clearer now 😃 Tested on iOS & Android.

**Comment by jlim521** [comment]
I've just tested it out and the animation is great! One thing that I would like to propose just one more is, I think there should be a logic to handle the component to not re-render itself if the `text` prop is the same. I have a timer on my component that's using the `marquee` component. Since the timer is updating itself on `state` and triggers the higher-order component to re-render as well, I think `marquee` is also being forced to re-render? Thought react would be smart enough to handle this on its own.

Regardless, I notice that when the timer is active, the marquee is being reset every tick (when the timer value increases), whereas it's animation is working as intended when the timer is paused. I believe if you just check on `shouldComponentUpdate` to see if the `text` has changed or not to determine if the component should update, it would be excellent! Thanks again for your effort, it's very much appreciated :)

**Comment by jlim521** [comment]
bump :) did you try to figure this out?

**Comment by cheng-kang** [comment]
Sorry, been busy writing my dissertation lately. I will be free from this Friday and will look at it ASAP. 😄
